# Generated by Django 5.1.5 on 2025-09-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='estimated_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='picture',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
